---
- name: Testing andrewrothstein.luarocks
  hosts: all
  vars:
    luarocks_install:
      - luajson
      - lua-resty-http
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'luarocks --version'
      ansible.builtin.command: luarocks --version
      changed_when: false
      register: luarocks_test_output
    - name: Output from 'luarocks --version'
      ansible.builtin.debug:
        msg: '{{ luarocks_test_output.stdout }}'
