---
- hosts: all
  vars:
    luarocks_install:
      - luajson
      - lua-resty-http
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/luarocks --version
      register: luarocks_test_output
    - debug:
        msg: '{{ luarocks_test_output.stdout }}'
