---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/luarocks --version
      register: luarocks_test_output
    - debug:
        msg: '{{ luarocks_test_output.stdout }}'
