---
# tasks file for luarocks
- name: Installing andrewrothstein.curl
  ansible.builtin.include_role:
    name: andrewrothstein.curl
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.luajit
  ansible.builtin.include_role:
    name: andrewrothstein.luajit
- name: Look for {{ luarocks_target_exe }}...
  become: true
  ansible.builtin.stat:
    path: '{{ luarocks_target_exe }}'
  changed_when: false
  register: luarocks_binary
- name: Installing luarocks
  when: not luarocks_binary.stat.exists
  block:
    - name: Downloading {{ luarocks_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ luarocks_url }}'
        dest: '{{ luarocks_tmp_tgz }}'
        mode: '644'
        checksum: '{{ luarocks_checksum }}'
    - name: Unarchiving {{ luarocks_tmp_tgz }} to {{ luarocks_src_parent }}'
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ luarocks_tmp_tgz }}'
        dest: '{{ luarocks_src_parent }}'
    - name: Configuring in {{ luarocks_src }}...
      become: true
      become_user: root
      ansible.builtin.command: >-
        ./configure
        --lua-suffix={{ luarocks_lua_suffix }}
        --with-lua-include={{ luarocks_lua_include }}
      args:
        chdir: '{{ luarocks_src }}'
        creates: '{{ luarocks_src }}/config.unix'
    - name: Make build install in {{ luarocks_src }}...
      become: true
      become_user: root
      ansible.builtin.command: >-
        make
        build
        install
      args:
        chdir: '{{ luarocks_src }}'
        creates: '{{ luarocks_target_exe }}'
  always:
    - name: Rm -f...
      become: true
      become_user: root
      with_items:
        - '{{ luarocks_tmp_tgz }}'
        - '{{ luarocks_src }}'
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
- name: Installing some rocks..
  become: true
  become_user: root
  with_items: '{{ luarocks_install | default([]) }}'
  ansible.builtin.command: >-
    luarocks install {{ item }}
  args:
    creates: /usr/local/lib/luarocks/rocks/{{ item }}
