---
# tasks file for luarocks
- name: download tgz...
  become: yes
  become_user: root
  get_url:
    url: '{{luarocks_url}}'
    dest: /tmp/{{luarocks_tgz}}
    checksum: '{{luarocks_checksum}}'

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{luarocks_tgz}}
    dest: '{{luarocks_src_parent}}'

- name: configure...
  become: yes
  become_user: root
  command: >-
    ./configure
    --lua-suffix={{luarocks_lua_suffix}}
    --lua-version={{luarocks_lua_ver}}
    --with-lua-include={{luarocks_lua_include}}
  args:
    chdir: '{{luarocks_src_parent}}/{{luarocks_name}}'
    creates: '{{luarocks_src_parent}}/{{luarocks_name}}/config.unix'

- name: make,install...
  become: yes
  become_user: root
  command: make build install
  args:
    chdir: '{{luarocks_src_parent}}/{{luarocks_name}}'
    creates: /usr/local/bin/luarocks
