---
# tasks file for luarocks
- name: download tgz...
  become: yes
  become_user: root
  get_url:
    url: '{{luarocks_url}}'
    dest: /tmp/{{luarocks_tgz}}
    checksum: '{{luarocks_checksum}}'

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    copy: no
    src: /tmp/{{luarocks_tgz}}
    dest: '{{luarocks_src_parent}}'

- name: configure...
  become: yes
  become_user: root
  command: >-
    ./configure
    --lua-suffix=jit
    --lua-version=2.0
    --force-config
  args:
    chdir: '{{luarocks_src_parent}}/{{luarocks_name}}'
    creates: '{{luarocks_src_parent}}/{{luarocks_name}}/config.unix'

- name: make...
  become: yes
  become_user: root
  command: make build
  args:
    chdir: '{{luarocks_src_parent}}/{{luarocks_name}}'

- name: install..
  become: yes
  become_user: root
  command: make install
  args:
    chdir: '{{luarocks_src_parent}}/{{luarocks_name}}'
