---
# tasks file for luarocks
- name: download tgz...
  become: yes
  become_user: root
  get_url:
    url: '{{luarocks_url}}'
    dest: /tmp/{{luarocks_tgz}}
    checksum: '{{luarocks_checksum}}'

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{luarocks_tgz}}
    dest: '{{luarocks_src_parent}}'

- name: configure...
  become: yes
  become_user: root
  command: ./configure {{ luarocks_configure }}
  args:
    chdir: '{{luarocks_src}}'
    creates: '{{luarocks_src}}/config.unix'

- name: make,install...
  become: yes
  become_user: root
  command: make build install
  args:
    chdir: '{{luarocks_src}}'
    creates: /usr/local/bin/luarocks

- name: cleanup
  become: yes
  become_user: root
  with_items:
    - /tmp/{{luarocks_tgz}}
    - '{{luarocks_src}}'
  file:
    path: '{{item}}'
    state: absent
